language: ruby
sudo: false
cache: bundler
rvm:
- 2.1
script: bundle exec middleman build
deploy:
- provider: s3
  access_key_id: AKIAIU7AAOIVL3TVPKIA
  secret_access_key:
    secure: "cmmaKi3k4RlCtXLmFTGrmlW/mCrJQTOo5YpqAxSdghjmWdd+NwWMHW0p4x7y6+LoBs9y8Cs96qe9IQ02Ofa04hVFQ490wX1YuRcJS/vPT9CEb8V3cpr1gp1fVB5mKJxcnx3NAWAlBegqt7B/TMGPqSJl1odulVZUGdkDYxlfeN8nONbaMamWzRFAhjLW9voVqmzy7H75MpOQAtf6SRf7iXpBreM2va2ZgnzRZH/7YcGbNaqLtaxhZQNPylEBYK9ZT/bD8TY0wrglHrXkvkS8Vka4j/8t5P3TQ1LFx6i3F6vmWwekcewjCANL2nz/mWm08qEwMTUbh4QC7q9gywUK5OdR8opaIr7Dr9v/lMqKSddCtBSYakI9rmJhY2KfGd6Q/Hkku7EE1gepnFjVvENgZ7MNU5qz741MUxjbqanHHKWCv9Kx/p1eFrRRd81BJR4CRvGJoNOaUrB8WYqOMs1uI0v42mr6J09siepaF3ClasTRedDYg5MHUS6jKq01H2aO4VQGjX7Cptl8jnEhh0i6ADsKcBBVO9QfMwBqHApQEylnHBvdxUzpku3j/j/BOUZ80JVYqQBUam5B4UyLwQFcpBUsXY5npJgFhAwozFg/UcYzK7oKhUnClTcu6K98vHxajcgfk6I+HvXEhadhWD85Qu9jzA8HMxjEDqEi6QHyXKA="
  bucket: beta.lgbtq.fm
  local-dir: build
  skip_cleanup: true
  on:
    all_branches: true
- provider: s3
  access_key_id: AKIAIU7AAOIVL3TVPKIA
  secret_access_key:
    secure: "cmmaKi3k4RlCtXLmFTGrmlW/mCrJQTOo5YpqAxSdghjmWdd+NwWMHW0p4x7y6+LoBs9y8Cs96qe9IQ02Ofa04hVFQ490wX1YuRcJS/vPT9CEb8V3cpr1gp1fVB5mKJxcnx3NAWAlBegqt7B/TMGPqSJl1odulVZUGdkDYxlfeN8nONbaMamWzRFAhjLW9voVqmzy7H75MpOQAtf6SRf7iXpBreM2va2ZgnzRZH/7YcGbNaqLtaxhZQNPylEBYK9ZT/bD8TY0wrglHrXkvkS8Vka4j/8t5P3TQ1LFx6i3F6vmWwekcewjCANL2nz/mWm08qEwMTUbh4QC7q9gywUK5OdR8opaIr7Dr9v/lMqKSddCtBSYakI9rmJhY2KfGd6Q/Hkku7EE1gepnFjVvENgZ7MNU5qz741MUxjbqanHHKWCv9Kx/p1eFrRRd81BJR4CRvGJoNOaUrB8WYqOMs1uI0v42mr6J09siepaF3ClasTRedDYg5MHUS6jKq01H2aO4VQGjX7Cptl8jnEhh0i6ADsKcBBVO9QfMwBqHApQEylnHBvdxUzpku3j/j/BOUZ80JVYqQBUam5B4UyLwQFcpBUsXY5npJgFhAwozFg/UcYzK7oKhUnClTcu6K98vHxajcgfk6I+HvXEhadhWD85Qu9jzA8HMxjEDqEi6QHyXKA="
  bucket: lgbtq.fm
  local-dir: build
  skip_cleanup: true
  on:
    branch: master
